[package]
name = "trjm"
version = "0.1.0"
edition = "2024"

[dependencies]
ecow = "0.2.3"
nom = "8"
pico-args = "0.5.0"
rustc-hash = "2.1.1"

[lints.clippy]
pedantic.level = "warn"
pedantic.priority = -1
missing_errors_doc = "allow"
wildcard_imports = "allow"
ignored_unit_patterns = "allow"
